apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-gateway-vs
  namespace: devops
spec:
  hosts:
    - "*"
  gateways:
    - devops/devops-gateway
  http:
    - match:
        - uri:
            prefix: /api/
      route:
        - destination:
            host: frontend-gateway
            subset: v1
            port:
              number: 80
