apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v2
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
      version: v2
  template:
    metadata:
      labels:
        app: service-a
        version: v2
    spec:
      containers:
        - name: service-a
          image: service-a:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
