apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-service-a-all-v2
  namespace: devops
spec:
  hosts:
    - service-a
  http:
    - route:
        - destination:
            host: service-a
            subset: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-service-b-all-v2
  namespace: devops
spec:
  hosts:
    - service-b
  http:
    - route:
        - destination:
            host: service-b
            subset: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-service-c-all-v2
  namespace: devops
spec:
  hosts:
    - service-c
  http:
    - route:
        - destination:
            host: service-c
            subset: v2
